version: "2"

networks:
    dockernet:
        external: true

services:

  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"

    networks:
      #- zeebe_network
      - dockernet
  